name: Main

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Build And Push Docker Image
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            hugovallada/rest-to-graph:${{github.run_number}}.0
            hugovallada/rest-to-graph:latest
