name: Release Go binaries

on:
  release:
    types: [created]

jobs:
  releases:
    name: Release Go Binary
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./cmd/app"
          binary_name: "server"
          ldflags: "-s -w"
